dependencies:
  - name: service-account
    version: 0.5.0
    repository: https://ibm-garage-cloud.github.io/toolkit-charts/
  - name: sonarqube
    version: 9.6.3
    repository: https://oteemo.github.io/charts
  - name: ocp-route
    version: 0.3.0
    repository: https://ibm-garage-cloud.github.io/toolkit-charts/
  - name: tool-config
    version: 0.9.0
    repository: https://ibm-garage-cloud.github.io/toolkit-charts/

